at_formula_list = {
	{
		name = "hastium",
		material1 = "magic_liquid_movement_faster",
		material2 = "magic_liquid_faster_levitation",
		output = "magic_liquid_faster_levitation_and_movement",
	},
	{
		material1 = "radioactive_liquid",
		material2 = "powder_empty",
		cauldron_contents = "sand",
		cauldron_material = "air",
		other = at_planterbox,
		output = "fungi_creeping",
	},
	{
		name = "silver1",
		material1 = "magic_liquid_random_polymorph",
		material2 = "diamond",
		output = "silver",
	},
	{
		name = "silver2",
		material1 = "magic_liquid_random_polymorph",
		material2 = "gold",
		output = "silver",
	},
	{
		name = "silver3",
		material1 = "copper",
		material2 = "brass",
		cauldron_contents = "water",
		output = "silver",
	},
	{
		name = "levi",
		material1 = "brass",
		material2 = "material_confusion",
		output = "magic_liquid_faster_levitation",
	},
	{
		material1 = "brass",
		material2 = "diamond",
		output = "purifying_powder",
	},
	{
		name = "void1",
		material1 = "radioactive_liquid",
		material2 = "blood_worm",
		cauldron_contents = "fungi",
		output = "void_liquid",
	},
	{
		name = "void2",
		material1 = "diamond",
		material2 = "magic_liquid_random_polymorph",
		cauldron_contents = "radioactive_liquid",
		output = "void_liquid",
	},
}
